### ISSUE TITLE
Destiny2.ReportOffensivePostGameCarnageReportPlayer

### ISSUE THREAD

**Issue by vpzed** [alexanderwe/the-traveler#21]
I saw your recent update and I wanted to give you a heads up on the ReportOffensivePostGameCarnageReportPlayer endpoint.

In the docs it lists the OAuth scope needed as **BnetWrite**.  Our Applications can't get this scope so I created an Issue to ask about it. 

https://github.com/Bungie-net/api/issues/332

Basically we can't use this endpoint.  Details in the issue linked above.

**Comment by alexanderwe** [comment]
Sorry for responding so late... 
You are right for sure and thanks for mentioning the issue here ! I did not correctly check if the scope is obtainable by everyone. I am thinking about a way to deal with the method in my code right now. Either I am going to comment it out in a newer version or completely delete it.

**Comment by alexanderwe** [comment]
I ended up deleting the method completely and will add it again if the scope is obtainable. 
Thanks again for mentioning 👍
