### ISSUE TITLE
Are all endpoints wrapped?

### ISSUE THREAD

**Issue by Native-Coder** [alexanderwe/the-traveler#38]
# Question
## Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| the-traveler      | 0.7.4
| Node           | 8.9.1
| Operating System | Ubuntu server 16.04 LTS

## Question
Is there a method to getMembershipDataById? It seems like several endpoints are not yet implemented

## Context
I play on PC and using the searchDestinyPlayer( Enums.BungieMembershipType.All ) does not return my PC account, only my XBox account. This is evidently by design, as [I'm not the only one who has noticed this behavior in the destiny 2 api](https://github.com/Bungie-net/api/issues/258). Even using Enums.BungieMembershipType.PC returns an empty array. I have read that using the getMembershipDataById endpoint will pull the PC account info.

**Comment by alexanderwe** [comment]
Hey @Native-Coder 👋 , 
you are right, this endpoint is missing. This is most likely the case because the endpoint is not strictly related to the Destiny2 API since it is located under the `user` resource. But I see why this endpoint might be a good fit to add to the library. I was also thinking about adding the other `user` endpoints as well, but for this I think I need to restructure the library a little bit.

Currently it is the time of the finals for my current semester but they are over in a few days. 
I am going to implement the endpoint you need as soon as possible.

**Comment by Native-Coder** [comment]
Same here. My finals will be over by the end of the week. Let me know when you get started, I'd love to help. This library looks incredibly promising. But it's severely lacking in documentation. I noticed that you were using JSDoc-style comments. Have you considered hosting the output of jsdoc somewhere? I have a hosted server and wouldn't mind to host it for you if you would like.

**Comment by alexanderwe** [comment]
Then good luck for your finals 🍀 
Sure, I will let you know when I start. 

I use [typedoc](http://typedoc.org) for generating my documentation from the jsdoc comments. It is hosted at https://alexanderwe.github.io/the-traveler/ using GitHub pages. I would prefer to keep it this way because it is the most easiest for me and I think it fits the purpose the best. But thanks a lot for your offer! Where do you see improvements for documentation ? 

I assume that the high number of packages are mostly coming from the devDependencies which are automatically installed, even if an end user may not really need them in production. I will have a look if I can remove some.

**Comment by Native-Coder** [comment]
HEEEEEY! Thats the documentation that I've been looking for!!! You should link that on the npm and github pages!

**Comment by alexanderwe** [comment]
You mean they are missing code examples how to use them ?

**Comment by Native-Coder** [comment]
Yes, thats exactly what I mean. :)

**Comment by alexanderwe** [comment]
Alright, I will add code examples to the documentation. In the end it should look like this.
![screenshot 2018-12-16 at 13 14 06](https://user-images.githubusercontent.com/12934015/50053377-7edf4780-0134-11e9-913b-750e484bced9.png)

**Comment by Native-Coder** [comment]
@alexanderwe  I ended up just [writing my own Bungie.net library](https://github.com/Native-Coder/node-bungie-lib). It's 0 dependency, and fully asynchronous. Check it out and let me know what you think. I could use some help testing and debugging all of the endpoints.

heres a link to the [documentation](https://dev.tylermeador.com/docs/bungie-net-api/)

**Comment by alexanderwe** [comment]
@Native-Coder Sorry for responding so late. Had a lot going on. 
Great to see you implementing something on your own ! It's always nice to have several approaches available. I will definitely take a look at your code and will tell you if I find something. 

I will close this issue for now.
