### ISSUE TITLE
Why does the-traveler require you to set the oAuth token instead of taking it as a parameter when oAuth API calls are made?

### ISSUE THREAD

**Issue by Native-Coder** [alexanderwe/the-traveler#41]
# Question
## Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| the-traveler      | 0.7.4
| Node           | 8.9.1
| Operating System | Ubuntu Server 16.04 LTS

## Question
Do you create a new traveler instance for each connected client?

I am, because you have to set `traveler_instance.oauth` to the oAuth token that you get from Bungie. Wouldn't it make more sense to pass your oAuth key to any oAuth API calls that you make so that we only need a single instance of the-traveler?

## Context
Each one of my websocket clients has their own instance of the-traveler, plus the web-socket server has it's own instance for manafest management. It would be ideal if the-traveler did not rely on having the oAuth token set, but instead took it as a parameter when making oAuth API calls.

**Comment by alexanderwe** [comment]
You are absolutely right, it would be a better API design to just take the oauth access token as a parameter. I will consider and implement this in the newer version of the library.

**Comment by Native-Coder** [comment]
Man you take feed backs so well. Thank you. Have you considered moving to vanilla JS instead of using typescript? The API almost has to be used server side anyway  since it requires your private key. I'd love to help port this to vanilla JS. It would be a lot easier to contribute to as well.

**Comment by alexanderwe** [comment]
Thanks, I try to do my best 

It might be the case that it is easier to contribute if the library would be written in plain JS, but Typescript offers a lot of nice features, like type safety and excellent tooling in VSCode and other editors and IDEs. Furthermore it can be ensured that less errors are made during coding because of the type system. So I would very much like to keep the library in Typescript. The npm sources are I  in plain JS either way, so there is no need to have plain JS implementation of the library, at least not from my point of view. But thanks for considering it 👍

**Comment by alexanderwe** [comment]
With the new [release](https://github.com/alexanderwe/the-traveler/releases/tag/v1.0.0) all OAuth related methods require the access token as a parameter now
