### ISSUE TITLE
Manifest JSON

### ISSUE THREAD

**Issue by Jakosaur** [alexanderwe/the-traveler#42]
https://github.com/Bungie-net/api/issues/785

The manifest now comes in a JSON format, tried to get this working but guessing it's only currently supported with .ZIP to extract the .content file. 

Maybe needs to have two different ways of handling it depending on the file type, so both work 👍

**Comment by alexanderwe** [comment]
Yeah, right now only the .zip version is handled. Since I will made some changes to the library in the future I will also include the .json version in it. Thanks for pointing out ✨

**Comment by Jakosaur** [comment]
Any updates on this? 🙂

**Comment by alexanderwe** [comment]
Hi, I am sorry that I didn't reply for such a long time. Yeah I already have fix for this ready on [feature/#38 ](https://github.com/alexanderwe/the-traveler/tree/feature/%2338). But I am currently a little bit busy with university and since I will introduce some breaking changes with the next version (just some proxy objects before some method calls, to clarify the distinction in their calls) I need to update some parts of the documentation. I try to push the new version at the end of this week or earlier. I hope you don't mind too much 🙂 

If you need the unpublished version earlier, you can head to the feature branch and download the sources. But then they are not fully tested

**Comment by Jakosaur** [comment]
That's absolutey fine, thanks for the update! 🙂

**Comment by alexanderwe** [comment]
@Jakosaur there is a dedicated method to download a .json Manifest now, see the [documentation](https://alexanderwe.github.io/the-traveler/classes/destiny2resource.html#downloadmanifestjson). 

If you find some issues with the code, please feel free to open a new issue or ask here 🙂
