### ISSUE TITLE
Implement a build in function to access the manifest

### ISSUE THREAD

**Issue by alexanderwe** [alexanderwe/the-traveler#6]
It would be a good thing to have a integrated way to access the Destiny Manifest right from the package

**Comment by vpzed** [comment]
I figured out a what I believe to be novel way to lookup entries in the manifest using the JSON query functions in SQLite which may be of use for this enhancement.   I've covered them in [this Gist](https://gist.github.com/vpzed/efb7b29f5dfda49633d62801ac30566c)  This bypasses the issue with the id column in the all but one of the tables not matching the value returned by the API.  

For example if you lookup a character in the API and are given a raceHash of 2803282938 you will have a problem because the row id in the DestinyRaceDefinition table corresponding to this entry is -1491684358 so if you perform a query like ```SELECT json FROM DestinyRaceDefinition WHERE id = 2803282938``` you will get nothing.  Using the query method in the Gist you can get the information back directly using the raceHash value without any guessing or transformations.

**Comment by alexanderwe** [comment]
Thanks for pointing me into the right direction and providing the Gist. I will definitely have a look at it when I start to implement it.
